### ISSUE TITLE
Unable to set speed w/Nano Every

### ISSUE THREAD

**Issue by nathanwray** [Coo-per/Jetson-Bolt-Pro-Mods#1]
First off, thank you for putting this together. Very cool.

The issue I'm having is that I can't get the speed to adjust. I'm currently targeting the 3mph setting since that seems like it would be easiest to visually verify that the setting is working.

The weird thing is I AM seeing the headlight flashing, so I'm talking to the controller and everything seems to be otherwise correct. But the speed, no matter what I set it to in the program, seems to stick at the default speed (I measured 14/15mph via GPS).

I'm not experienced with Arduino and I picked up a Nano Every just for this. I've tried both with ATMEGA328 emulation and without - I really have no idea if the issue is the Arduino. Or maybe my Jetson Bolt Pro has a different version controller. But it seems weird that the headlight command works but not the max speed setting.

Is it possible that there is some "unlock" step that is missing, or - ? I've got two Bolts, one untouched, so if I can help diagnose please let me know. 

Have others been successful setting the max speed on otherwise virgin bolt pros?

**Comment by Coo-per** [comment]
The gains really aren't too high or noticeable, but definitely setting to 3 you should see the wheel spin slowly. Also max speed is only realized with high State of Charge with a dip in speed as the voltage drops. So best results would be from a 2 battery setup.

Personally I've used it on 3 Jetsons: 1 was mine and the other 2 from friends.. first testing 3 mph, then setting to 19 mph all worked.

Only thing I'd think of is to increase the boot delay 200 ms -> 1000 ms or something
delay(200); // Wait for Jetson controller to boot

If you saw the lights flash it should have taken effect.. as you said, you are talking to the controller. How old is the bike? Not sure if newer bikes they patched speed adjustment- that would seem like a lot of work for Jetson to go through for no substantial reasoning.

**Comment by nathanwray** [comment]
Sorry, should have added. These were both bought at Costco in mid-July 2021 (this summer).

**Comment by Coo-per** [comment]
If I have some time later today or tomorrow I'll post code to read status to the computer. It's already partially there in Testing/ folder, but I have a few improvements as I learned more about what each message actually meant.
Then you can test the speeds - Measurements should be taken on a full charge on both bikes if you wanted to compare them.
---
The bike attempts to achieve max speed. With no weight (lifting back wheel of the ground) and full charge it does reach max speed. Increasing the weight will lower top speed. Also decreasing state of charge will lower top speed. That's why the speedhack seems a bit gimmicky without a powerful battery behind it. We are increasing the capability for a higher speed as the controller won't limit the acceleration up until the new speed, but a weak battery & weight of an adult may not allow it.
---
Let me know how it goes with the other bike.

**Comment by nathanwray** [comment]
For whatever reason, the attached was able to reliably set the max speed to 3mph and then (presumably) to 19mph on both bikes. At this point I don't think I have a speed sensor issue, or, maybe it spontaneously resolved.

Otherwise, I'm not sure what the issue was last week or why it resolved. As you can see in the attached I took a few steps to make sure the controller was up before sending the speed change, including a longer delay and before-and-after headlight flashes. I was also going down a road of seeing if the implicit narrowing to byte was causing a problem by trying to handle that explicitly, removing the int member from the array and overwriting the member instead.

Regardless with the attached I think I'm up and running. Thank you again for putting this together, very cool and much better than tracking down a bluetooth module.

[JetsonSpeedHack-working issue 1.zip](https://github.com/Coo-per/Jetson-Bolt-Pro-Mods/files/7516545/JetsonSpeedHack-working.issue.1.zip)
